--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 03. 30. 19:53:04
-- Server version: 5.5.5-10.4.27-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS r6;

CREATE DATABASE IF NOT EXISTS r6
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE r6;

--
-- Create table `teams`
--
CREATE TABLE IF NOT EXISTS teams (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Team VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `ranks`
--
CREATE TABLE IF NOT EXISTS ranks (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Rang VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `players`
--
CREATE TABLE IF NOT EXISTS players (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  TeamId INT(11) NOT NULL,
  RangId INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 801,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE players 
  ADD CONSTRAINT FK_players_rankanyad_id FOREIGN KEY (RangId)
    REFERENCES ranks(id);

--
-- Create foreign key
--
ALTER TABLE players 
  ADD CONSTRAINT FK_players_team_id FOREIGN KEY (TeamId)
    REFERENCES teams(id);

DELIMITER $$

--
-- Create procedure `GenTables`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE GenTables()
BEGIN
#delete
DELETE
  FROM players;
DELETE
  FROM ranks;
DELETE
  FROM teams;



#insert the ranks
INSERT INTO ranks (id, Rang)
  VALUES (1, 'Copper (V, IV, III, II, and I)'),
  (2, 'Bronze (V, IV, III, II, and I)'),
  (3, 'Silver (V, IV, III, II, and I)'),
  (4, 'Gold (V, IV, III, II, and I)'),
  (5, 'Platinum (V, IV, III, II, and I)'),
  (6, 'Emerald (V, IV, III, II, and I)'),
  (7, 'Diamond (V, IV, III, II, and I)'),
  (8, 'Champion (Only one level)');

#insert the teams
INSERT INTO teams
  VALUES (1, 'sirj')
  , (2, 'Team Liquid'),
  (3, 'PENTA Sports'),
  (4, 'SK Gaming'),
  (5, 'FaZe Clan');


#insert the players
INSERT INTO players (Name, TeamId, RangId)
  VALUES
  #Sirj
  ('Sirj_UzakiChan', 1, 4), ('Sirj_GasparBea', 1, 4), ('Sirj_szarjatek', 1, 3), ('Sirj_NB.akiraly', 1, 5), ('SIRJ_Davee.', 1, 5),
  #Team Liquid
  ('nesk', 2, 8), ('Paluh', 2, 8), ('resetz', 2, 8), ('Lagonis Captain', 2, 8), ('volpz', 2, 8),
  #PENTA Sports
  ('Pistol	', 3, 8), ('Kantoraketti ', 3, 8), ('Spaawn', 3, 8), ('Lion', 3, 8), ('Bugs', 3, 8),
  #SK Gaming
  ('Hotancold', 4, 8), ('Jarvis', 4, 8), ('Mint', 4, 8), ('Nyx', 4, 8), ('Pojoman', 4, 8),
  #FaZe Clan
  ('Cyber', 5, 8), ('soulz1', 5, 8), ('VITAKING', 5, 8), ('Handyy', 5, 8), ('KDS', 5, 8);

SELECT
  *
FROM players;
SELECT
  *
FROM asdasd;
SELECT
  *
FROM teams;


END
$$

DELIMITER ;

-- 
-- Dumping data for table teams
--
INSERT INTO teams VALUES
(1, 'sirj'),
(2, 'Team Liquid'),
(3, 'PENTA Sports'),
(4, 'SK Gaming'),
(5, 'FaZe Clan');

-- 
-- Dumping data for table ranks
--
INSERT INTO ranks VALUES
(1, 'Copper (V, IV, III, II, and I)'),
(2, 'Bronze (V, IV, III, II, and I)'),
(3, 'Silver (V, IV, III, II, and I)'),
(4, 'Gold (V, IV, III, II, and I)'),
(5, 'Platinum (V, IV, III, II, and I)'),
(6, 'Emerald (V, IV, III, II, and I)'),
(7, 'Diamond (V, IV, III, II, and I)'),
(8, 'Champion (Only one level)');

-- 
-- Dumping data for table players
--
INSERT INTO players VALUES
(776, 'Sirj_UzakiChan', 1, 4),
(777, 'Sirj_GasparBea', 1, 4),
(778, 'Sirj_szarjatek', 1, 3),
(779, 'Sirj_NB.akiraly', 1, 5),
(780, 'SIRJ_Davee.', 1, 5),
(781, 'nesk', 2, 8),
(782, 'Paluh', 2, 8),
(783, 'resetz', 2, 8),
(784, 'Lagonis Captain', 2, 8),
(785, 'volpz', 2, 8),
(786, 'Pistol\t', 3, 8),
(787, 'Kantoraketti ', 3, 8),
(788, 'Spaawn', 3, 8),
(789, 'Lion', 3, 8),
(790, 'Bugs', 3, 8),
(791, 'Hotancold', 4, 8),
(792, 'Jarvis', 4, 8),
(793, 'Mint', 4, 8),
(794, 'Nyx', 4, 8),
(795, 'Pojoman', 4, 8),
(796, 'Cyber', 5, 8),
(797, 'soulz1', 5, 8),
(798, 'VITAKING', 5, 8),
(799, 'Handyy', 5, 8),
(800, 'KDS', 5, 8);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;